<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NbPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbPageRepository extends EntityRepository
{
    public function getNbPage($id_prototype_access){
        $nbDepage = 0;
        $query = $this
            ->createQueryBuilder('nb')
            ->select('MAX(nb.nbDepage) as nbDepage')
            ->innerJoin('nb.prototypeAccess', 'pa')
            ->where('pa.id = :id_prototype_access ')
            ->setParameter('id_prototype_access', $id_prototype_access)
            ->setMaxResults(1)
            ->getQuery();
        $result = $query->getResult();

        foreach ($result as $resp)
        {
            if($resp['nbDepage'] != '') $nbDepage = $resp['nbDepage'];
        }

        return $nbDepage;
    }

    public function getAllNbPageByPrototypeAccess($id_prototype_access)
    {
        $query = $this
            ->createQueryBuilder('nb')
            ->select('nb')
            ->innerJoin('nb.prototypeAccess', 'pa')
            ->where('pa.id = :id_prototype_access ')
            ->setParameter('id_prototype_access', $id_prototype_access)
            ->getQuery();
        return $query->getResult();
    }
}
