<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrototypeAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrototypeAccessRepository extends EntityRepository {

    public function getNbProtoParSociete($id_societe) {
        $query = $this
                ->createQueryBuilder('pa')
                ->select('pa')
                ->innerJoin('pa.societe', 's')
                ->where('s.id = :id_societe')
                ->setParameter('id_societe', $id_societe)
                ->getQuery();
        return count($query->getResult());
    }
    
    public function getNbSocieteAvecPrototype() {
        $query = $this
                ->createQueryBuilder('pa')
                ->select('distinct s.id as id_societe, s.description as description')
                ->innerJoin('pa.societe', 's')
                ->getQuery();
        return $query->getResult();
    }
    

}
