<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends EntityRepository
{
    public function getSelecteurs()
    {
        $secteur_query="select secteur.id_secteur as id_secteur, secteur.libelle_secteur as libelle_secteur from secteur";
        return $this->fetch($secteur_query);
    }

    private function fetch($query)
    {
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        return  $stmt->fetchAll();
    }
}
