<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuffixeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuffixeRepository extends EntityRepository
{
    public function findSuffixeThematiqueBySociete($id_soc)
    {
        $query = $this
            ->createQueryBuilder('sf')
            ->select('distinct sf.id as id_suffixe, sf.libelleSuffixe as libelle_suffixe ')
            ->innerJoin('sf.suffixeSocietes', 'sfs')
            ->innerJoin('sfs.societe', 's')
            ->where('s.id = :id_soc')
            ->setParameter('id_soc', $id_soc)
            ->groupBy('sf.libelleSuffixe')
            ->getQuery();
      
        return $query->getResult();
    }

    private function fetch($query)
    {
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        return  $stmt->fetchAll();
    }

    public function getSuffixesBySociete($id_societe)
    {
        $suffixe_query="select suffixe.id_suffixe as id_suffixe, suffixe.libelle_suffixe as libelle_suffixe from suffixe 
									INNER JOIN suffixe_societe ON suffixe_societe.id_suffixe = suffixe.id_suffixe and suffixe_societe.id_societe != $id_societe
									GROUP BY libelle_suffixe ";
        return $this->fetch($suffixe_query);
    }
}
