<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuffixeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuffixeRepository extends EntityRepository
{
    public function findSuffixeThematiqueBySociete($id_soc)
    {
        echo $id_soc."<br/>";
        $query = $this
            ->createQueryBuilder('sf')
            ->select('distinct sf.id as id_suffixe, sf.libelleSuffixe as libelle_suffixe ')
            ->innerJoin('sf.suffixeSocietes', 'sfs')
            ->innerJoin('sfs.societe', 's')
            ->where('s.id = :id_soc')
            ->setParameter('id_soc', $id_soc)
            ->groupBy('sf.libelleSuffixe')
            ->getQuery();
        return $query->getResult();
    }
}
