<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository {

    public function findThemeThematiqueByPrototypeAccess($id_prototype_access) {
        $query = $this
                ->createQueryBuilder('t')
                ->select('distinct t.id as id_theme, t.libelleTheme as libelle_theme, s.id as id_societe, s.description as societe,p.id as id_prototype_access')
                ->innerJoin('t.lexiques', 'l')
                ->innerJoin('l.societe', 's')
                ->innerJoin('l.prototypeAccess', 'p')
                ->where('p.id = :id_prototype_access')
                ->setParameter('id_prototype_access', $id_prototype_access)
                ->getQuery();

        return $query->getResult();
    }

    public function findAllTheme() {
        $query = $this
                ->createQueryBuilder('t')
                ->select('t.id as id_theme, t.libelleTheme as libelle_theme')
                ->groupBy('t.id')
                ->orderBy('t.libelleTheme', 'asc')
                ->getQuery();

        return $query->getResult();
    }

    public function findAllLE($nom_prototype, $id_theme, $id_societe) {
        $nom_prototype = strtolower($nom_prototype);
        $nom_prototype = trim($nom_prototype);
        if ($id_theme == "" && $id_societe != "") {
            $query = $this
                    ->createQueryBuilder('t')
                    ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                    ->innerJoin('t.lexiques', 'l')
                    ->innerJoin('l.societe', 's')
                    ->where('s.id = :id_societe AND s.id != 653')
                    ->setParameter('id_societe', $id_societe)
                    ->groupBy('t.id')
                    ->getQuery();

            if ($nom_prototype != "") {
                $query = $this
                        ->createQueryBuilder('t')
                        ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                        ->innerJoin('t.lexiques', 'l')
                        ->innerJoin('l.prototypeAccess', 'pa')
                        ->innerJoin('l.societe', 's')
                        ->where('s.id = :id_societe AND s.id != 653')
                        ->andWhere('lower(pa.type) LIKE :nom_prototype ')
                        ->setParameter('nom_prototype','%'.$nom_prototype.'%')
                        ->setParameter('id_societe', $id_societe)
                        ->groupBy('t.id')
                        ->getQuery();
            }
        }


        if ($id_theme != "" && $id_societe == "") {
            $query = $this
                    ->createQueryBuilder('t')
                    ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                    ->innerJoin('t.lexiques', 'l')
                    ->innerJoin('l.societe', 's')
                    ->where('t.id = :id_theme AND s.id != 653')
                    ->setParameter('id_theme', $id_theme)
                    ->groupBy('t.id')
                    ->getQuery();

            if ($nom_prototype != "") {
                $query = $this
                        ->createQueryBuilder('t')
                        ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                        ->innerJoin('t.lexiques', 'l')
                        ->innerJoin('l.societe', 's')
                        ->innerJoin('l.prototypeAccess', 'pa')
                        ->where('t.id = :id_theme AND s.id != 653')
                        ->andWhere('lower(pa.type) LIKE :nom_prototype ')
                        ->setParameter('nom_prototype','%'.$nom_prototype.'%')
                        ->setParameter('id_theme', $id_theme)
                        ->groupBy('t.id')
                        ->getQuery();
            }
        }

        if ($id_theme != "" && $id_societe != "") {
            $query = $this
                    ->createQueryBuilder('t')
                    ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                    ->innerJoin('t.lexiques', 'l')
                    ->innerJoin('l.societe', 's')
                    ->where('t.id = :id_theme AND s.id = :id_societe AND s.id != 653')
                    ->setParameter('id_theme', $id_theme)
                    ->setParameter('id_societe', $id_societe)
                    ->groupBy('t.id')
                    ->getQuery();
            if ($nom_prototype != "") {
                $query = $this
                        ->createQueryBuilder('t')
                        ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                        ->innerJoin('t.lexiques', 'l')
                        ->innerJoin('l.societe', 's')
                        ->innerJoin('l.prototypeAccess', 'pa')
                        ->where('t.id = :id_theme AND s.id = :id_societe AND s.id != 653')
                        ->andWhere('lower(pa.type) LIKE :nom_prototype ')
                        ->setParameter('nom_prototype','%'.$nom_prototype.'%')
                        ->setParameter('id_theme', $id_theme)
                        ->setParameter('id_societe', $id_societe)
                        ->groupBy('t.id')
                        ->getQuery();
            }
        }

        if ($id_theme == "" && $id_societe == "") {
            $query = $this
                    ->createQueryBuilder('t')
                    ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                    ->innerJoin('t.lexiques', 'l')
                    ->innerJoin('l.societe', 's')
                    ->where('s.id != 653')
                    ->groupBy('t.id')
                    ->getQuery();
            if ($nom_prototype != "") {
                $query = $this
                        ->createQueryBuilder('t')
                        ->select('t.libelleTheme as libelle_theme, t.id as id_theme, s.id as id_societe, s.description as description')
                        ->innerJoin('t.lexiques', 'l')
                        ->innerJoin('l.societe', 's')
                        ->innerJoin('l.prototypeAccess', 'pa')
                        ->where('s.id != 653')
                        ->andWhere('lower(pa.type) LIKE :nom_prototype ')
                        ->setParameter('nom_prototype','%'.$nom_prototype.'%')
                        ->groupBy('t.id')
                        ->getQuery();
            }
        }


        return $query->getResult();
    }
    private function fetch($query)
    {
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        return  $stmt->fetchAll();
    }
    function getLibelleTheme($id_theme){
        $libelle_theme = "";
        $sql = "SELECT libelle_theme FROM theme where id_theme='$id_theme'" ;
        $results = $this->fetch($sql);
        foreach ($results as $resp) {
            $libelle_theme = $resp['libelle_theme'];
        }
        return $libelle_theme;
    }

}
