<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabulaireEnvirUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulaireEnvirUsageRepository extends EntityRepository
{
    public function getVocabulaireEnvirUsageByVocabulaire($id_vocabulaire) {
        $query = $this
                ->createQueryBuilder('veu')
                ->select('v.id as id_vocabulaire, e.libelleEnvironnementUsage as libelle_env_usage')
                ->innerJoin('veu.vocabulaire', 'v')
                ->innerJoin('veu.environnement_usage', 'e')
                ->where('v.id = :id_vocabulaire')
                ->setParameter('id_vocabulaire', $id_vocabulaire)
                ->getQuery();

        return $query->getResult();
    }

    public function modifyOneCritere($id_vocabulaire) {
        $query = $this
                ->createQueryBuilder('veu')
                ->select('distinct e.libelleEnvironnementUsage as libelle_env_usage')
                ->innerJoin('veu.vocabulaire', 'v')
                ->innerJoin('veu.environnement_usage', 'e')
                ->where('v.id = :id_vocabulaire')
                ->setParameter('id_vocabulaire', $id_vocabulaire)
                ->groupBy("v.id")
                ->getQuery();

        return $query->getResult();
    }
}

