<?php

namespace Formation\VocabulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabulaireDepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulaireDepartementRepository extends EntityRepository
{
    public function getVocabulaireDepartementByVocabulaire($id_vocabulaire) {
        $query = $this
                ->createQueryBuilder('vd')
                ->select('v.id as id_vocabulaire, d.libelleDepartement as libelle_departement')
                ->innerJoin('vd.vocabulaire', 'v')
                ->innerJoin('vd.departement', 'd')
                ->where('v.id = :id_vocabulaire')
                ->setParameter('id_vocabulaire', $id_vocabulaire)
                ->getQuery();

        return $query->getResult();
    }

    public function modifyOneCritere($id_vocabulaire) {
        $query = $this
                ->createQueryBuilder('vd')
                ->select('distinct d.libelleDepartement as libelle_departement')
                ->innerJoin('vd.vocabulaire', 'v')
                ->innerJoin('vd.departement', 'd')
                ->where('v.id = :id_vocabulaire')
                ->setParameter('id_vocabulaire', $id_vocabulaire)
                ->groupBy("v.id")
                ->getQuery();

        return $query->getResult();
    }
}

