<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabulaireSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulaireSocieteRepository extends EntityRepository
{
}
