<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabulairePhraseSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulairePhraseSourceRepository extends EntityRepository
{
}
