<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabulaireFonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulaireFonctionRepository extends EntityRepository
{
}
